name: CI

on:
  push:
    branches:
      - main

jobs:
  ci:
    name: Build and Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
          fetch-depth: 0

      - name: Setup PNPM
        run: corepack enable && corepack prepare --activate

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          check-latest: true
          registry-url: https://registry.npmjs.org
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build packages
        run: pnpm build

      - name: Create release Pull Request or publish to NPM
        id: changesets
        uses: changesets/action@v1
        with:
          publish: pnpm release
          commit: "ci(changesets): version packages"
          title: "ci(changesets): version packages"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GHCR_TOKEN }}

